{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d0750c6-79eb-43e1-89d9-c1227b2726aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "from torch.utils.data import DataLoader\n",
    "from clinical_trial_dataset import ClinicalTrialDataset\n",
    "from collate_fn import clinical_trial_collate\n",
    "from Models.mmf.early_fusion import EarlyFusion, get_encoder_dict as earlyfusion_get_encoders\n",
    "from Models.mmf.middle_fusion import MiddleFusion, get_encoder_dict as middlefusion_get_encoders\n",
    "from Models.mmf.late_fusion import LateFusion, get_encoder_dict as latefusion_get_encoders\n",
    "from Models.mpnn import MPNN\n",
    "from Models.mmcto.mmcto import MMCTO\n",
    "import numpy as np\n",
    "from sklearn.metrics import average_precision_score, roc_auc_score, f1_score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e098edd-5126-4dbe-956e-df2aa360eb06",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_loaders(phase=\"I\", batch_size=32, dataset_name=\"hint\"):\n",
    "    train_dataset = ClinicalTrialDataset(\n",
    "        data_dir=\"data/clinical-trial-outcome-prediction/data_reduced\" if dataset_name==\"hint\" else \"data/labelling/labelling_reduced\",\n",
    "        phase=phase,\n",
    "        split=\"train\",\n",
    "        dataset_name=dataset_name\n",
    "    )\n",
    "    val_dataset = ClinicalTrialDataset(\n",
    "        data_dir=\"data/clinical-trial-outcome-prediction/data_reduced\" if dataset_name==\"hint\" else \"data/labelling/labelling_reduced\",\n",
    "        phase=phase,\n",
    "        split=\"valid\",\n",
    "        dataset_name=dataset_name\n",
    "    )\n",
    "    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=clinical_trial_collate)\n",
    "    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, collate_fn=clinical_trial_collate)\n",
    "    return train_loader, val_loader\n",
    "\n",
    "\n",
    "def get_model(model_type=\"early\", fusion_dim=768):\n",
    "    device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "    mpnn_model = MPNN(device=device)\n",
    "\n",
    "    if model_type == \"early\":\n",
    "        encoders = earlyfusion_get_encoders(mpnn_model)\n",
    "        model = EarlyFusion(encoders=encoders, fusion_dim=fusion_dim)\n",
    "    elif model_type == \"middle\":\n",
    "        encoders = middlefusion_get_encoders(mpnn_model)\n",
    "        model = MiddleFusion(encoders=encoders, fusion_dim=fusion_dim)\n",
    "    elif model_type == \"late\":\n",
    "        encoders = latefusion_get_encoders(mpnn_model)\n",
    "        model = LateFusion(encoders=encoders, fusion_dim=fusion_dim)\n",
    "    elif model_type == \"mmcto\":\n",
    "        encoders = earlyfusion_get_encoders(mpnn_model)\n",
    "        model = MMCTO(encoders=encoders)\n",
    "    else:\n",
    "        raise ValueError(f\"Unknown model_type: {model_type}\")\n",
    "\n",
    "    return model.to(device)\n",
    "\n",
    "\n",
    "def evaluate(model, loader):\n",
    "    model.eval()\n",
    "    preds, labels = [], []\n",
    "    device = next(model.parameters()).device\n",
    "\n",
    "    with torch.no_grad():\n",
    "        for batch in loader:\n",
    "            batch = {k: (v.to(device) if isinstance(v, torch.Tensor) else v) for k, v in batch.items()}\n",
    "            if isinstance(model, MMCTO):\n",
    "                output = model(batch, batch[\"label\"])\n",
    "                pred = output[\"metric_dict\"][\"preds\"]\n",
    "            else:\n",
    "                output = model(batch)\n",
    "                pred = output[\"probs\"]\n",
    "\n",
    "            preds.append(pred.cpu())\n",
    "            labels.append(batch[\"label\"].cpu())\n",
    "\n",
    "    preds = torch.cat(preds)\n",
    "    labels = torch.cat(labels)\n",
    "\n",
    "    roc_auc = roc_auc_score(labels.numpy(), preds.numpy())\n",
    "    pr_auc = average_precision_score(labels.numpy(), preds.numpy())\n",
    "    f1 = f1_score(labels.numpy(), (preds.numpy() > 0.5).astype(int))\n",
    "\n",
    "    return roc_auc, pr_auc, f1\n",
    "\n",
    "\n",
    "def train(model, train_loader, val_loader, epochs=5):\n",
    "    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)\n",
    "    device = next(model.parameters()).device\n",
    "    best_val_score = -np.inf\n",
    "    best_model = None\n",
    "\n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        for batch in train_loader:\n",
    "            batch = {k: (v.to(device) if isinstance(v, torch.Tensor) else v) for k, v in batch.items()}\n",
    "            optimizer.zero_grad()\n",
    "            if isinstance(model, MMCTO):\n",
    "                output = model(batch, batch[\"label\"])\n",
    "                loss = output[\"loss_dict\"][\"classification_loss\"]\n",
    "            else:\n",
    "                output = model(batch)\n",
    "                loss = output[\"loss\"]\n",
    "\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "\n",
    "        val_roc_auc, val_pr_auc, val_f1 = evaluate(model, val_loader)\n",
    "        print(f\"[Epoch {epoch}] Val ROC-AUC: {val_roc_auc:.4f}, PR-AUC: {val_pr_auc:.4f}, F1: {val_f1:.4f}\")\n",
    "\n",
    "        if val_pr_auc > best_val_score:\n",
    "            best_val_score = val_pr_auc\n",
    "            best_model = model.state_dict()\n",
    "\n",
    "    return best_model\n",
    "\n",
    "\n",
    "def main():\n",
    "    model_types = [\"early\", \"middle\", \"late\", \"mmcto\"]\n",
    "    phases = [\"I\", \"II\", \"III\"]\n",
    "    datasets = [\"hint\", \"ctod\"]\n",
    "\n",
    "    for dataset_name in datasets:\n",
    "        print(f\"\\n### Dataset: {dataset_name.upper()} ###\")\n",
    "        results = {}\n",
    "\n",
    "        for model_type in model_types:\n",
    "            results[model_type] = {}\n",
    "            for phase in phases:\n",
    "                print(f\"\\n==== Training {model_type.upper()} on Phase {phase} ====\")\n",
    "                train_loader, val_loader = get_loaders(phase=phase, batch_size=32, dataset_name=dataset_name)\n",
    "                model = get_model(model_type=model_type)\n",
    "                best_model = train(model, train_loader, val_loader, epochs=10)\n",
    "                model.load_state_dict(best_model)\n",
    "\n",
    "                roc_auc, pr_auc, f1 = evaluate(model, val_loader)\n",
    "                results[model_type][phase] = (roc_auc, pr_auc, f1)\n",
    "\n",
    "        print(\"\\n=== Final Results ===\")\n",
    "        for model_type, phase_results in results.items():\n",
    "            print(f\"\\nModel: {model_type.upper()}\")\n",
    "            for phase, (roc, pr, f1_) in phase_results.items():\n",
    "                print(f\"Phase {phase} -> ROC AUC: {roc:.4f}, PR AUC: {pr:.4f}, F1: {f1_:.4f}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
